//! Public-API-level differential acceptance test for the round 4 number
//! corpus, plus provenance for `meridian-core/src/json_number_corpus_data.rs`.
//!
//! [`meridian_core::migration::checks`]'s JSON canonicality check
//! (`crate::json::is_canonical`, exercised through the public
//! [`ContentEnvelope`] constructor) must ACCEPT `{"n":<expected>}` for every
//! `(bits, expected)` pair in the corpus — i.e. `f64::from_bits(bits)`
//! re-serializes to EXACTLY `expected`, the real `JSON.stringify` output for
//! that value. `meridian-core/src/json.rs`'s own
//! `matches_the_node_reference_for_a_large_deterministic_bit_pattern_corpus`
//! unit test additionally checks this directly against `js_number_to_string`
//! (the private function under test); this file re-checks the SAME corpus
//! through the crate's actual public boundary, so the fix is verified at
//! both the internal-function level and the public-API level, not just one.
//!
//! The corpus was generated by the following script, run once with a real
//! Node.js (V8's `JSON.stringify` — i.e. genuine ECMA-262 `Number::toString`
//! — is the ground truth for every `expected` string; nothing here is
//! reconstructed by Rust logic):
//!
//! ```js
//! // Deterministic differential corpus generator for js_number_to_string.
//! // PRNG: mulberry32, fixed seed -> reproducible sequence of raw f64 bit
//! // patterns -> filtered to finite, nonzero -> ground truth via real
//! // JSON.stringify (V8's Number::toString). Emits a Rust `const` array.
//!
//! function mulberry32(seed) {
//!   let a = seed >>> 0;
//!   return function () {
//!     a |= 0; a = (a + 0x6D2B79F5) | 0;
//!     let t = Math.imul(a ^ (a >>> 15), 1 | a);
//!     t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
//!     return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
//!   };
//! }
//!
//! const rand = mulberry32(0xC0FFEE);
//! function randU32() { return (rand() * 0x100000000) >>> 0; }
//! function randBits() {
//!   const hi = BigInt(randU32());
//!   const lo = BigInt(randU32());
//!   return (hi << 32n) | lo;
//! }
//!
//! const buf = new ArrayBuffer(8);
//! const dv = new DataView(buf);
//! function bitsToF64(bits) {
//!   dv.setBigUint64(0, bits, false);
//!   return dv.getFloat64(0, false);
//! }
//!
//! const seen = new Set();
//! const entries = [];
//!
//! function addBits(bits) {
//!   bits = BigInt.asUintN(64, bits);
//!   if (seen.has(bits.toString())) return;
//!   const x = bitsToF64(bits);
//!   if (!Number.isFinite(x) || x === 0) return;
//!   seen.add(bits.toString());
//!   entries.push([bits, JSON.stringify(x)]);
//! }
//!
//! // 1) Broad random sample of raw bit patterns (any exponent/mantissa,
//! //    excluding NaN/Infinity, both signs occur naturally from the sign bit).
//! const RANDOM_COUNT = 6000;
//! for (let i = 0; i < RANDOM_COUNT; i++) {
//!   addBits(randBits());
//! }
//!
//! // 2) The originally-discovered round-to-even tie counterexample, plus its
//! //    immediate bit-pattern neighbours (nextafter in both directions) to
//! //    densely sample the exact region where the bug was found.
//! const tieBits = 0xC2D3B4AD20110E28n; // -86666878403640.625
//! for (let d = -8n; d <= 8n; d++) {
//!   addBits(BigInt.asUintN(64, tieBits + d));
//! }
//!
//! // 3) Exact powers of ten (and their neighbours) from 1e-30 to 1e30, which
//! //    exercise the ECMA case A/B/C/D boundaries most densely.
//! for (let e = -30; e <= 30; e++) {
//!   const x = Number(`1e${e}`);
//!   if (x !== 0 && Number.isFinite(x)) {
//!     const v = new DataView(new ArrayBuffer(8));
//!     v.setFloat64(0, x, false);
//!     const bits = v.getBigUint64(0, false);
//!     addBits(bits);
//!     addBits(bits + 1n);
//!     addBits(bits - 1n);
//!   }
//! }
//!
//! // 4) Subnormal range and its boundary with normal numbers.
//! addBits(1n); // smallest positive subnormal, 5e-324
//! addBits(0x000FFFFFFFFFFFFFn); // largest subnormal
//! addBits(0x0010000000000000n); // smallest positive normal
//! addBits(0x7FEFFFFFFFFFFFFFn); // largest finite double
//!
//! entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
//! // ... (emits the Rust `const NUMBER_CORPUS` array to
//! // meridian-core/src/json_number_corpus_data.rs — see that file's header)
//! ```
//!
//! This produced 6201 entries (6000 random + 17 tie-region + ~183 power-of-ten
//! region + 4 subnormal/normal boundary, minus a handful of duplicate bit
//! patterns collapsed by the `seen` set).

use meridian_core::migration::{ContentEnvelope, Encoding};
use meridian_core::types::{ContentDigest, NonEmptyString};

include!("../src/json_number_corpus_data.rs");

#[test]
fn every_corpus_entry_is_accepted_as_canonical_json_through_the_public_api() {
    for &(bits, expected) in NUMBER_CORPUS {
        let x = f64::from_bits(bits);
        let content = format!("{{\"n\":{expected}}}");
        let digest = ContentDigest::of_str(&content);
        let result = ContentEnvelope::new(
            NonEmptyString::new("application/json").unwrap(),
            Encoding::Utf8,
            NonEmptyString::new(content.as_str()).unwrap(),
            digest,
        );
        assert!(
            result.is_ok(),
            "expected {content:?} (bits=0x{bits:016x}, x={x:e}) to be accepted \
             as canonical JSON (matching the real checkContentEnvelope), got {:?}",
            result.unwrap_err()
        );
    }
}
